language: julia

os:
  - linux
  - osx

julia:
  - 0.4
  - 0.5
  - nightly

notifications:
  email: false

after_success:
  - julia -e 'cd(Pkg.dir("WeakRefStrings")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("WeakRefStrings")); include(joinpath("docs", "make.jl"))'
